import { Product } from "./types/Products";

export const sampleProducts: Product[] = [
    {
        name: 'Nike Slim Shirt',
        slug: 'nike-slim-shirt',
        category: 'Shirts',
        image: '../image/p1.jpg',
        price: 120,
        countInStock: 10,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
    },
    {
        name: 'Lacost ',
        slug: 'lacost',
        category: 'Shirts',
        image: '../image/p2.jpg',
        price: 120,
        countInStock: 10,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
    },
    {
        name: 'Pink',
        slug: 'pink',
        category: 'Shirts',
        image: '../image/p2.jpg',
        price: 120,
        countInStock: 10,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
    },
    {
        name: 'Brown',
        slug: 'brown',
        category: 'Shirts',
        image: '../image/p4.jpg',
        price: 120,
        countInStock: 10,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
    },
]