import { Product } from "./types/Product";

export const sampleProducts: Product[] = [
    {
        name: 'Sony SRS-XB13.',
        slug: 'sony-speaker',
        category: 'Shirts',
        image: '../image/speaker.jpg',
        price: 120,
        countInStock: 1,
        brand: 'nike',
        rating: 5.5,
        numReviews: 10,
        description: 'high quality shirt',
    },
    {
        name: 'Sony SRS-XB13 EXTRA BASS Wireless Bluetooth Portable Lightweight Compact Travel Speaker.',
        slug: 'lacost',
        category: 'Shirts',
        image: '../image/speaker.jpg',
        price: 120,
        countInStock: 10,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
    },
    {
        name: 'Sony SRS-XB13 EXTRA BASS Wireless Bluetooth Portable Lightweight Compact Travel Speaker.',
        slug: 'pink',
        category: 'Shirts',
        image: '../image/speaker.jpg',
        price: 120,
        countInStock: 10,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
    },
    {
        name: 'Sony SRS-XB13 EXTRA BASS Wireless Bluetooth Portable Lightweight Compact Travel Speaker.',
        slug: 'brown',
        category: 'Shirts',
        image: '../image/speaker.jpg',
        price: 120,
        countInStock: 10,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
    },
]